name: FastAPI CI/CD Pipeline

on:
  push:
  pull_request:

jobs:
  validate:
    name: Validate Docker Stack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq
          mkdir -p ~/.docker/cli-plugins
          curl -sSL https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose
          docker compose version

      - name: Validate Docker Stack
        run: docker compose -f infra/docker-compose.yml config

      - name: Build & start containers
        run: docker compose -f infra/docker-compose.yml up postgres redis api -d --build

      - name: Wait for API healthcheck
        run: |
          for i in {1..60}; do
            if curl -fs http://localhost:8000/healthz >/dev/null; then
              echo "✅ API healthy"
              exit 0
            fi
            echo "Waiting for API... ($i/60)"
            sleep 2
          done
          echo "❌ API failed to respond" >&2
          docker compose -f infra/docker-compose.yml logs api || true
          exit 1

      - name: Verify API endpoints
        run: |
          echo "Testing API root endpoint..."
          curl -s http://localhost:8000/ | jq .
          echo "Testing health endpoint..."
          curl -s http://localhost:8000/healthz | jq .

      - name: Cleanup
        if: always()
        run: docker compose -f infra/docker-compose.yml down -v || true

  api-healthcheck:
    name: Run API healthcheck (Full Stack)
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq
          mkdir -p ~/.docker/cli-plugins
          curl -sSL https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose
          docker compose version

      - name: Run API healthcheck (postgres + redis + api)
        run: |
          set -euo pipefail
          docker compose -f infra/docker-compose.yml up postgres redis api -d
          cleanup() {
            local exit_code=$1
            if [ "$exit_code" -ne 0 ]; then
              docker compose -f infra/docker-compose.yml logs api || true
              docker compose -f infra/docker-compose.yml logs postgres || true
              docker compose -f infra/docker-compose.yml logs redis || true
            fi
            docker compose -f infra/docker-compose.yml down -v || docker compose -f infra/docker-compose.yml down || true
          }
          trap 'cleanup $?' EXIT
          for i in {1..60}; do
            if curl -fs http://localhost:8000/healthz >/dev/null; then
              echo "✅ API healthy"
              exit 0
            fi
            echo "Waiting for API... ($i/60)"
            sleep 2
          done
          echo "❌ API failed to respond" >&2
          exit 1
